ORG 07C00H ;指示位置
MOV AX , CS;
MOV DS , AX;
MOV ES , AX;
CALL SHOW_HELLO;
JMP $;

SHOW_HELLO:
    MOV AX,MES_HELLO
    MOV BP,AX; 导入字符串
    MOV CX,len_HELLO
    MOV AX,01301H;
    MOV BX,000cH;
    MOV DX,0H;
    INT 10H;
    RET;


MES_HELLO: DB "HELLO, THIS IS OS WORLD"
len_HELLO  equ  $ - MES_HELLO 

DW 0xAA55